classdef (Sealed) cModelResults < cMessageLogger
    %cModelResults - Internal container for thermoeconomic model results.
    %   Stores the cResultInfo objects generated by cThermoeconomicModel
    %   and indexes them by ResultId. The container keeps the current
    %   model result set consistent by clearing the aggregate result when
    %   a state-level result changes.
    %
    %   cModelResults methods:
    %     cModelResults   - Construct the results container from a cDataModel
    %     getResults      - Retrieve one stored cResultInfo or the full cell array
    %     setResults      - Store a cResultInfo in the container
    %     clearResults    - Remove one stored cResultInfo from the container
    %     getModelResults - Return the current state-level result objects
    %
    %   See also cThermoeconomicModel, cResultSet, cResultInfo, cDataModel
    %
    properties(Access=private)
        results    % cResultInfo cell array container
    end

    methods
        function obj = cModelResults(data)
        %cModelResults - Construct the results container from a cDataModel.
        %   Validates the input model, allocates the result storage array,
        %   and seeds the container with the data-model result object.
        %
        %   Syntax:
        %     obj = cModelResults(data)
        %
        %   Input Arguments:
        %     data - Valid cDataModel object
        %
        %   Output Arguments:
        %     obj - cModelResults object. Check isValid(obj) after
        %           construction.
        
            % Check inputs
            if ~isObject(data,'cDataModel')
                obj.messageLog(cType.ERROR,cMessages.InvalidObject,class(data));
                return
            end
            % Create results array
            obj.results=cell(1,cType.MAX_RESULT_INFO);
            dm=getResultInfo(data);
            obj.setResults(dm);
        end

        function res=getResults(obj,id)
        %getResults - Retrieve stored result objects from the container.
        %   With no input, returns the full internal cell array. With a
        %   valid ResultId, returns the cResultInfo stored at that index.
        %   Syntax:
        %     res = obj.getResults(id)
        %   Input Arguments:
        %     id - ResultId index to retrieve (optional)
        %   Output Arguments:
        %     res - Stored cResultInfo object, or the full result cell
        %           array when no index is provided
        %
            res=cType.EMPTY;
            if nargin==1
                res=obj.results;
            elseif isIndex(id,1,cType.MAX_RESULT_INFO)
                res=obj.results{id};
            end
        end

        function res=clearResults(obj,id)
        %clearResults - Remove a stored result object from the container.
        %   If the cleared result is state-level, the aggregate model result
        %   is also cleared to keep the container consistent.
        %   Syntax:
        %     res = obj.clearResults(id)
        %   Input Arguments:
        %     id - ResultId index to remove
        %   Output Arguments:
        %     res - Previously stored cResultInfo object
            if ~isIndex(id,1,cType.MAX_RESULT_INFO)
                return
            end
            res=obj.getResults(id);
            if ~isempty(res)
                obj.results{id}=cType.EMPTY;
                if id<=cType.MAX_RESULT
                    obj.clearResults(cType.ResultId.RESULT_MODEL);
                end
            end
        end

        function setResults(obj,res,force)
        %setResults - Store a cResultInfo object using its ResultId as key.
        %   Replaces the current entry only when the new object differs
        %   from the stored one, unless force is true.
        %   Syntax:
        %     obj.setResults(res)
        %     obj.setResults(res,force)
        %   Input Arguments:
        %     res   - cResultInfo object to store
        %     force - Optional logical flag to store without comparison
        %       true | false (default)
        %
            if ~isObject(res,'cResultInfo')
                return
            end
            if nargin==2
                force=false;
            end
            id=res.ResultId;
            res0=obj.results{id};
            if force || cModelResults.checkAssign(res0,res)
                obj.results{id}=res;
                if id<=cType.MAX_RESULT
                    obj.clearResults(cType.ResultId.RESULT_MODEL);
                end
            end
        end

        function res=getModelResults(obj)
        %getModelResults - Return the state-level result objects.
        %   Excludes the data-model result and returns only the results
        %   associated with the active state/sample configuration.
        %   Syntax:
        %     res = obj.getModelResults
        %   Output Arguments:
        %     res - Cell array with the current cResultInfo objects
        %   
            stateResults=obj.results(1:cType.MAX_RESULT);
            res=obj.results(~cellfun(@isempty,stateResults));
        end
    end

    methods(Static,Access=private)
        function res = checkAssign(obj1,obj2)
        %checkAssign - Determine whether a stored result should be replaced.
        %   Returns true when obj1 is empty or when obj2 is a valid
        %   cResultInfo object that differs from obj1.
        %   Syntax:
        %     res = cModelResults.checkAssign(obj1,obj2)
        %   Input Arguments:
        %     obj1 - Current cResultInfo object
        %     obj2 - New cResultInfo object
        %   Output Arguments:
        %     res  - true when obj2 should replace obj1
        %           
            % Check if obj2 is valid
            if ~isObject(obj2,'cResultInfo')
                res=false;
                return
            end
            % If obj1 is empty do assign
            if isempty(obj1)
                res=true;
                return
            end
            % Compare if objects are different
            res=(obj1~=obj2);
        end
    end
end